version: '3'
services: 
    web:
        build: .
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules
            # . é o equivalente ao PWD
            - .:/app
