sudo: required
services:
    - docker

language: generic
before_install:
    - openssl aes-256-cbc -K $encrypted_91799929af02_key -iv $encrypted_91799929af02_iv -in multi-k8s-288016-a54a1bc0a001.json.enc -out multi-k8s-288016-a54a1bc0a001.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubeclt
    - gcloud auth activate-service-account --key-file multi-k8s-288016-a54a1bc0a001.json
    - gcloud config set project multi-k8s-288016
    - gcloud config set compute/zone us-central1-c
    - gcloud container cluster get-credentials multi-k8s
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t filipebsouza/multi-client -f ./complex/client/Dockerfile.dev ./complex/client
script:
    - docker run -e CI=true filipebsouza/react-test npm run test

after_success:
    - docker build -t filipebsouza/multi-client ./complex/client
    - docker build -t filipebsouza/multi-nginx ./complex/nginx
    - docker build -t filipebsouza/multi-server ./complex/server
    - docker build -t filipebsouza/multi-worker ./complex/worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push then to docker hub
    - docker push filipebsouza/multi-client
    - docker push filipebsouza/multi-nginx
    - docker push filipebsouza/multi-server
    - docker push filipebsouza/multi-worker

deploy:
    provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY # Variáveis de ambiente no Travis CI
    secret_access_key: "$AWS_SECRET_KEY" # Variáveis de ambiente no Travis CI
    region: "sa-east-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-sa-east-1-507454525147" # Esse nome fica no S3
    bucket_path: "docker-multi" # Na primeira vez na tem nada
    on:
        branch: master
# Para serviços extenos eu uso o IAM (Identity and Access Management) da AWS
