sudo: required
services:
    - docker
    
language: generic
before_install:
    - docker build -t filipebsouza/docker-react .

script:
    - docker run -e CI=true filipebsouza/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY # Variáveis de ambiente no Travis CI
    secret_access_key: 
        secure: "$AWS_SECRET_KEY" # Variáveis de ambiente no Travis CI
    region: "sa-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-sa-east-1-507454525147" # Esse nome fica no S3
    bucket_path: "docker-react" # Na primeira vez na tem nada
    on:
        branch: master
# Para serviços extenos eu uso o IAM (Identity and Access Management) da AWS