sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t filipebsouza/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true filipebsouza/docker-react npm run test -- --coverage