version: '3'
services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - '3000:3000'
        # Precisei desse cara no Windows
        tty: true
        volumes: 
            - /app/node_modules
            # . é o equivalente ao PWD
            - .:/app
    # tests:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     tty: true
    #     volumes: 
    #         - /app/node_modules
    #         # . é o equivalente ao PWD
    #         - .:/app
    #     command: ["npm", "run", "test"]
