FROM node:alpine

WORKDIR '/app'

ENV PATH /app/node_modules/.bin:$PATH

COPY ./frontend/package.json ./
RUN npm install --silent
RUN npm install test --watchAll

COPY ./frontend ./

CMD ["npm", "run", "start"]